Pages
Devoxx4Kids-NPO/littil-frontend pull request #36
Opened 2022-09-12 15:40 UTC by jackvdberg

PR for pages:

- About us
- Information
- Information for schools
- Information for specialists
- Information for sponsors

2022-09-14 15:16 UTC, Anjanas-dh requested changes

2022-09-14 16:00 UTC, jackvdberg commented on src/app/pages/website/website.module.ts
> +import {CommonModule} from '@angular/common';
Ik zal het voor imports alvast even fixen aan mijn kant

2022-09-14 16:26 UTC, jackvdberg commented on src/app/pages/website/about-us/about-us.module.ts
> +    ButtonModule,
Deze gaat over de buttonmodule denk ik? die gebruik ik op line 41 in about-us.component.html

2022-09-14 16:31 UTC, jackvdberg commented on src/app/pages/website/about-us/about-us.component.scss
> +.content {
Klopt hoor, ik bedoelde meer dat zonder die content class op de <div>, je voor iedere <p> en <h2> binnen de div dezelfde tailwind classes moet definiëren. Ik weet niet of je het liever zo hebt of dat je zegt zet het maar per element in de template :)

2022-09-15 06:24 UTC, Anjanas-dh requested changes

2022-09-15 06:24 UTC, Anjanas-dh commented on src/app/pages/website/about-us/about-us.component.scss
> +.content {
Ah zo! Als het algemene styling is, mag het op het hoogste niveau (styles.scss) zonder een class eromheen

2022-09-15 06:24 UTC, Anjanas-dh commented on src/app/pages/website/info/information/information.component.html
> +<littil-content-container outerClasses="mb-3">
Hier ook de littil-title gebruiken zoals in about-us. Voor consistentie

2022-09-15 06:24 UTC, Anjanas-dh commented on src/app/pages/website/info/schools/schools.component.html
> +<littil-content-container outerClasses="mb-3">
Hier ook de littil-title gebruiken zoals in about-us. Voor consistentie

2022-09-15 06:24 UTC, Anjanas-dh commented on src/app/pages/website/info/specialists/specialists.component.html
> +<littil-content-container outerClasses="mb-3">
Hier ook de littil-title gebruiken zoals in about-us. Voor consistentie

2022-09-15 06:24 UTC, Anjanas-dh commented on src/app/pages/website/info/sponsors/sponsors.component.html
> +<littil-content-container outerClasses="mb-3">
Hier ook de littil-title gebruiken zoals in about-us. Voor consistentie

2022-09-15 06:24 UTC, Anjanas-dh commented on src/app/pages/website/about-us/about-us.module.ts
> +    ButtonModule,
Check ik zie hem nu :)

2022-09-15 19:04 UTC, Anjanas-dh approved these changes

2022-09-15 19:04 UTC, merged