Pages
Devoxx4Kids-NPO/littil-frontend pull request #38
Opened 2022-09-25 13:23 UTC by jackvdberg

Draft PR for branch pages containing:

- 404 page
- contact page
- devoxx4kids page

2022-09-26 07:09 UTC, Anjanas-dh requested changes

2022-09-26 07:09 UTC, Anjanas-dh commented on src/app/pages/website/contact/contact.component.spec.ts
> +      declarations: [ ContactComponent ]
je mist hier de fromComponents, denk dat de test daarom faalt? FromModule en ReactiveFormsModule ook.

2022-09-26 07:09 UTC, Anjanas-dh commented on src/app/pages/website/contact/contact.component.ts
> +    this.contactForm = this.contactForm = this.fb.group({
Je kunt ook gewoon een FromGroup({}) maken zonder de formBuilder? Het formulier is niet complex genoeg en je voorkomt zo dat je "this.contactForm?" moet doen overal.

2022-09-26 07:09 UTC, Anjanas-dh commented on src/app/pages/website/not-found/not-found.component.html
> +          <p class="mt-1 text-base text-gray-500">Please check the URL in the address bar and try again.</p>
Opeens engels? :P

2022-09-26 07:09 UTC, Anjanas-dh commented on src/app/pages/website/website.routing.ts
> +        path: '**',
De notfound mag (ook) op het hoogste niveau: app-routing.module.ts

2022-09-26 07:09 UTC, Anjanas-dh commented on src/app/pages/website/contact/contact.component.ts
> +    this.contactForm = this.contactForm = this.fb.group({
Voorbeeld:
`registerForm: FormGroup = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
  });`

2022-09-26 16:48 UTC, jackvdberg commented on src/app/pages/website/not-found/not-found.component.html
> +          <p class="mt-1 text-base text-gray-500">Please check the URL in the address bar and try again.</p>
oopsie

2022-10-01 10:05 UTC, Anjanas-dh approved these changes

2022-10-01 10:05 UTC, merged