Add pictures and infra lead
Devoxx4Kids-NPO/littil-frontend pull request #84
Opened 2023-09-19 19:08 UTC by LDMGN

2023-09-22 12:11 UTC, MarcelWildenburg requested changes

2023-09-22 12:11 UTC, MarcelWildenburg commented on src/app/pages/website/about-us/about-us.component.html
> +    vrijwilligers. Mocht dit initiatief jouw interesse gewekt hebben en wil jij hieraan meehelpen, neem dan contact met
Deze tekst moeten we nog even aanpassen.  Staat een beetje raar als we live gaan met de melding dat we er naar streven om in 2022 live te gaan. Kunnen we zondag wel doen bij de hackaton.

2023-09-24 12:15 UTC, tubbynl approved these changes

2023-09-24 12:15 UTC, tubbynl commented on src/app/pages/website/about-us/about-us.component.html
> -    <h2>Alle hulp is welkom</h2>
dit is de tekst review change van @MarcelWildenburg , ook verplaatst naar littil-contact-banner

2023-09-24 12:16 UTC, merged